"""add payment and tenant balance

Revision ID: ceb6041f35cf
Revises: e1f2a3b4c5d6
Create Date: 2026-04-14 17:39:37.532596

"""
from alembic import op
import models as models
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ceb6041f35cf'
down_revision = 'e1f2a3b4c5d6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allocation_records',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('operator_id', models.types.StringUUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='allocation_record_pkey')
    )
    with op.batch_alter_table('allocation_records', schema=None) as batch_op:
        batch_op.create_index('alloc_member_idx', ['account_id'], unique=False)
        batch_op.create_index('alloc_tenant_created_idx', ['tenant_id', 'created_at'], unique=False)

    op.create_table('payment_orders',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('provider', sa.String(length=20), nullable=False),
    sa.Column('out_trade_no', sa.String(length=64), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('account_id', models.types.StringUUID(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=20, scale=6), nullable=False),
    sa.Column('amount_fen', sa.Integer(), nullable=False),
    sa.Column('subject', sa.String(length=256), nullable=False),
    sa.Column('provider_trade_no', sa.String(length=64), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('qr_code', sa.String(length=512), nullable=True),
    sa.Column('prepay_raw', models.types.LongText(), nullable=True),
    sa.Column('notify_raw', models.types.LongText(), nullable=True),
    sa.Column('paid_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('client_ip', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='payment_order_pkey')
    )
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.create_index('payment_order_out_trade_no_idx', ['out_trade_no'], unique=True)
        batch_op.create_index('payment_order_provider_trade_idx', ['provider', 'provider_trade_no'], unique=False)
        batch_op.create_index('payment_order_tenant_status_idx', ['tenant_id', 'status'], unique=False)

    op.create_table('tenant_balances',
    sa.Column('id', models.types.StringUUID(), nullable=False),
    sa.Column('tenant_id', models.types.StringUUID(), nullable=False),
    sa.Column('balance', sa.Numeric(precision=20, scale=6), server_default='0', nullable=False),
    sa.Column('locked', sa.Numeric(precision=20, scale=6), server_default='0', nullable=False),
    sa.Column('total_topup', sa.Numeric(precision=20, scale=6), server_default='0', nullable=False),
    sa.Column('currency', sa.String(length=10), server_default='CNY', nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.PrimaryKeyConstraint('id', name='tenant_balance_pkey')
    )
    with op.batch_alter_table('tenant_balances', schema=None) as batch_op:
        batch_op.create_index('tenant_balance_tenant_id_idx', ['tenant_id'], unique=True)

    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scope', sa.String(length=20), server_default='user', nullable=False))

    # ### end Alembic commands ###

    # --- Data backfill: promote existing UserBalance rows into TenantBalance.locked ---
    # Rationale: the new tenant-level wallet replaces the per-user balance model.
    # To avoid losing historical funds, for every user with balance > 0 we find their
    # earliest owner tenant and credit that tenant's `locked` pool, so owners can
    # re-allocate to members explicitly. A matching AllocationRecord documents it.
    conn = op.get_bind()
    rows = conn.execute(sa.text(
        """
        SELECT ub.account_id, ub.balance
        FROM user_balances ub
        WHERE ub.balance > 0
        """
    )).fetchall()

    for row in rows:
        tenant_row = conn.execute(sa.text(
            """
            SELECT tenant_id FROM tenant_account_joins
            WHERE account_id = :aid AND role = 'owner'
            ORDER BY created_at ASC LIMIT 1
            """
        ), {"aid": row.account_id}).fetchone()

        if not tenant_row:
            continue

        tenant_id = tenant_row.tenant_id
        amount = row.balance

        conn.execute(sa.text(
            """
            INSERT INTO tenant_balances (id, tenant_id, balance, locked, total_topup, currency)
            VALUES (gen_random_uuid(), :tid, 0, :amt, :amt, 'CNY')
            ON CONFLICT (tenant_id) DO UPDATE
            SET locked = tenant_balances.locked + EXCLUDED.locked,
                total_topup = tenant_balances.total_topup + EXCLUDED.total_topup,
                updated_at = CURRENT_TIMESTAMP
            """
        ), {"tid": tenant_id, "amt": amount})

        conn.execute(sa.text(
            """
            INSERT INTO allocation_records (id, tenant_id, account_id, operator_id, amount, description)
            VALUES (gen_random_uuid(), :tid, :aid, :aid, :amt, '数据迁移：历史余额转入')
            """
        ), {"tid": tenant_id, "aid": row.account_id, "amt": amount})


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('billing_records', schema=None) as batch_op:
        batch_op.drop_column('scope')

    with op.batch_alter_table('tenant_balances', schema=None) as batch_op:
        batch_op.drop_index('tenant_balance_tenant_id_idx')

    op.drop_table('tenant_balances')
    with op.batch_alter_table('payment_orders', schema=None) as batch_op:
        batch_op.drop_index('payment_order_tenant_status_idx')
        batch_op.drop_index('payment_order_provider_trade_idx')
        batch_op.drop_index('payment_order_out_trade_no_idx')

    op.drop_table('payment_orders')
    with op.batch_alter_table('allocation_records', schema=None) as batch_op:
        batch_op.drop_index('alloc_tenant_created_idx')
        batch_op.drop_index('alloc_member_idx')

    op.drop_table('allocation_records')
    # ### end Alembic commands ###
